//
//  INTGoogleAnalyticsHandler.h
//  MyAppAnalytics
//
//  Created by Shankar Mallick on 21/11/14.
//  Copyright (c) 2014 Shankr_ios. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "GAI.h"
#import "GAIFields.h"
#import "GAIDictionaryBuilder.h"

@interface INTGoogleAnalyticsHandler : NSObject

/**
 *  Setting this property is MANDATORY in App Delegate.Sets the tracking to the Shared instance of the Google analytics tracker. This method should be called only once form the Application didifinish with launching mehtod. this method also sets the dispatch interval and tracks the uncaught exceptions and the Logging level is set to VERBOSE.
 */

@property (strong,nonatomic)NSString * trackingID;

/**
 *  User id of the user. TO BE SET ONLY ONCE .Required to deduplicate the ananlytics data for the particular user. Let the case be a user using the same app from multiple devices we would like the data for that particular user be unique. Set this property to a user ID generated by the system. WARNING : Never user personally identificable data that may uniquely identify the user. else google may terminate the account.
 */
@property (strong,nonatomic)NSString *userId;


/**
 *  The tracker for this App. For the most general purpose uses we have only one tracker per app. This file should be modified if we are supposed to have multiple trackers.
 */
@property (strong,nonatomic) id<GAITracker> tracker;

+ (INTGoogleAnalyticsHandler *)sharedInstance;

/**
 *  Required to track a particular event. Helpful in cases when it is required to track an event such as button click or purchase or some other user intent.
 *
 *  @param eventCategory_ Event category is a distinguishing feature of the event. Example the event may be calssified into categoty Audio/Video of the event is play or pause for some actions.
 *  @param actionName_    Name of the Action that is Play/Pause/Exit etc. it reflets the intent of the user
 *  @param lblName_       Optional
 *  @param value_         Some value if reqiured.
 */


-(void)trackClickEvent:(NSString *)eventCategory_ Action:(NSString *)actionName_ Label:(NSString *)lblName_ Value:(int)value_;

/**
 *  Required to track a particular screen in an app. Needed to get the info when a user a viewing a particular view. In this way we can track the user interaction of particular screen. So it will be known that wich of the particular screens in the app are being tracked.
 *
 *  @param screenName_ The screen name of the particular view. cannot be nil.
 */

-(void)trackScreen:(NSString *)screenName_;
@end
